name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group: {}

jobs:
  # Windows
  build_windows_clang:
    name: "🖥️ Windows (Clang)"
    uses: ./.github/workflows/windows-build-clang.yaml
    if: github.repository == 'OpenGOAL-Mods/OG-Mod-Base'
    with:
      cmakePreset: "Release-windows-clang"
      cachePrefix: ""
    secrets: inherit

  build_windows_msvc:
    name: "🖥️ Windows (MSVC)"
    uses: ./.github/workflows/windows-build-msvc.yaml
    if: github.repository == 'OpenGOAL-Mods/OG-Mod-Base'
    with:
      cmakePreset: "Release-windows-msvc"
      cachePrefix: ""
    secrets: inherit

  # Linux
  build_linux_clang:
    name: "🐧 Linux (Clang)"
    uses: ./.github/workflows/linux-build-clang.yaml
    if: github.repository == 'OpenGOAL-Mods/OG-Mod-Base'
    with:
      cmakePreset: "Release-linux-clang-asan"
      cachePrefix: ""
    secrets: inherit

  build_linux_gcc:
    name: "🐧 Linux (GCC)"
    uses: ./.github/workflows/linux-build-gcc.yaml
    if: github.repository == 'OpenGOAL-Mods/OG-Mod-Base'
    with:
      cmakePreset: "Release-linux-gcc"
      cachePrefix: ""
    secrets: inherit

  # MacOS
  build_macos_intel:
    name: "🍎 MacOS"
    uses: ./.github/workflows/macos-build.yaml
    if: github.repository == 'OpenGOAL-Mods/OG-Mod-Base'
    with:
      cmakePreset: "Release-macos-clang"
      cachePrefix: ""

  # Q4 2023 there will hopefully be native arm64 runners
  # https://github.com/github/roadmap/issues/528
  # build_macos_arm:
  #   name: "🍎 MacOS"
  #   uses: ./.github/workflows/macos-build-arm.yaml
  #   with:
  #     cmakePreset: "Release-macos-clang"
  #     cachePrefix: ""
